---
- name: >-
    Create
    {{ btrfs_subvolume.path }}/../snapshots/{{
    btrfs_subvolume.path | basename }}
  file:
    path: >-
      {{ btrfs_subvolume.path }}/../snapshots/{{
      btrfs_subvolume.path | basename }}
    state: directory
  when: btrfs_subvolume.snapshot | default(true)
  become: true

- name: >
    Start and enable
    btrfs-subvolume-snapshot@{{ btrfs_subvolume.escaped_path }}.timer
  systemd:
    name: btrfs-subvolume-snapshot@{{ btrfs_subvolume.escaped_path }}.timer
    state: started
    enabled: true
    daemon_reload: true
  when: btrfs_subvolume.snapshot | default(true)
  become: true

- name: >
    Stop and disable
    btrfs-subvolume-snapshot@{{ btrfs_subvolume.escaped_path }}.timer
  systemd:
    name: btrfs-subvolume-snapshot@{{ btrfs_subvolume.escaped_path }}.timer
    state: stopped
    enabled: false
    daemon_reload: true
  when: not (btrfs_subvolume.snapshot | default(true))
  become: true
