---
- name: >
    Start and enable
    btrfs-subvolume-delete@{{ btrfs_subvolume.escaped_path }}.timer
  systemd:
    name: btrfs-subvolume-delete@{{ btrfs_subvolume.escaped_path }}.timer
    state: started
    enabled: true
    daemon_reload: true
  when: btrfs_subvolume.delete | default(true)
  become: true

- name: >
    Stop and disable
    btrfs-subvolume-delete@{{ btrfs_subvolume.escaped_path }}.timer
  systemd:
    name: btrfs-subvolume-delete@{{ btrfs_subvolume.escaped_path }}.timer
    state: stopped
    enabled: false
    daemon_reload: true
  when: not (btrfs_subvolume.delete | default(true))
  become: true
