# There's three conerns to consider when deciding how to name units:
#
# * Compatibility. Various file systems place restrictions on which characters
#   may appear in file names. Unit names should use a conservative set of
#   characters, so as to avoid violating compatibility constraints.
# * Uniqueness. Unit names should never conflict with each other.
# * Usability. Unit names should be human-readable.
#
# A hash is compatible and unique. A (good) path transformation is compatible
# and usable. This module uses the latter.

- name: Install btrfs-progs
  pacman:
    name: btrfs-progs
    state: present
  become: true

- name: Set escaped paths for btrfs subvolumes
  set_fact:
    btrfs_subvolumes: '{{ btrfs_subvolumes | set_escaped_paths }}'

- include_tasks: btrfs-subvolume-delete.yml
  with_items: '{{ btrfs_subvolumes }}'

- include_tasks: btrfs-subvolume-snapshot.yml
  with_items: '{{ btrfs_subvolumes }}'
