---
- name: Install btrfs-progs
  pacman:
    name: btrfs-progs
    state: present
  become: true

- name: Set escaped paths for btrfs subvolumes
  set_fact:
    btrfs_subvolumes: '{{ btrfs_subvolumes | set_escaped_paths }}'

- name: Install script to delete old subvolumes
  copy:
    src: btrfs-subvolume-delete.py
    dest: /usr/local/bin/
    mode: 0755
  become: true

- name: Install template units to create and delete snapshots
  copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
  loop:
    - btrfs-subvolume-delete@.service
    - btrfs-subvolume-delete@.timer
    - btrfs-subvolume-snapshot@.service
    - btrfs-subvolume-snapshot@.timer
  become: true

- include_tasks: btrfs-subvolume-delete.yml
  loop: '{{ btrfs_subvolumes }}'
  loop_control:
    loop_var: btrfs_subvolume

- include_tasks: btrfs-subvolume-snapshot.yml
  loop: '{{ btrfs_subvolumes }}'
  loop_control:
    loop_var: btrfs_subvolume
