---
version: '3'

services:
  consul:
    image: jaudet/consul
    build: consul
    hostname: "${my_hostname:?}"
    command:
      - "-server"
      - "-advertise"
      - "${my_ip:?}"
      - "-bootstrap-expect"
      - "3"
    volumes:
      - data:/data
    ports:
      - '53:53/udp'
      - '8300:8300/tcp'
      - '8301:8301/tcp'
      - '8301:8301/udp'
      - '8302:8302/tcp'
      - '8302:8302/udp'
      - '8400:8400/tcp'
      - '8500:8500/tcp'

volumes:
  data:
