---
apiVersion: v1
kind: Service
metadata:
  name: cloud-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  # select label from pod definition
  selector:
    project: qsk-book
