- name: Install crda
  pacman:
    name: crda

- name: Configure crda
  copy:
    src: wireless-regdom
    dest: /etc/conf.d/wireless-regdom
    owner: root
    group: root
    mode: 0644
  notify: Set wireless regulatory domain
