---

- block:

  - name: Uninstall unused packages
    pacman:
      name:
        - maven
        - jdk8-openjdk
        - sbt
        - scala
      state: absent

  - name: Install development tools
    pacman:
      name:
        - ansible
        - ansible-lint
        - bandwidth
        - cmark
        - ctags
        - desktop-file-utils
        - devtools
        - entr
        - git
        - graphviz
        - ipv6calc
        - mypy
        - namcap
        - pacman-contrib
        - python-docutils  # for rst2html
        - python-passlib  # for ansible's htpasswd module
        - python-pylint
        - python-rst2pdf
        - python-wheel
        - python36
        - shellcheck
        - sshpass  # optional for ansible
        - tmux
        - twine
        - vim
        - vim-badwolf-git
        - vim-hemisu-git
        - vim-jellybeans
        - vim-mark
        - vim-nerdtree
        - vim-tagbar
        - vim-undotree
        - wget
        - yamllint
    notify: Set install reason for optional dependencies

  become: true
