---
- name: Sync all repositories
  pacman:
    update_cache: true
  become: true

- name: Sync ichi-private repository
  command: pacman -Sy --config /etc/pacman.d/ichi-private.conf
  become: true

- name: Sync ichi-public repository
  command: pacman -Sy --config /etc/pacman.d/ichi-public.conf
  become: true
