- block:

  - name: Install syncthing
    pacman:
      name: syncthing

  - name: Set inotify watch limit now and at next boot
    sysctl:
      name: fs.inotify.max_user_watches
      # A 64-bit OS uses about 1 KB of memory per inode.
      value: 65536
      sysctl_file: /etc/sysctl.d/50-syncthing.conf
      state: present
    notify: Set inotify watch limit now

  # See comments in borg-backup/tasks/main.yml for explanation of why the systemd
  # module isn't used for these tasks.
  - name: Start syncthing for certain users
    command: >
      machinectl shell "{{ item }}"@.host /usr/bin/systemctl --user
      start syncthing
    with_items: "{{ syncthing_usernames }}"

  - name: Enable syncthing for certain users
    command: >
      machinectl shell "{{ item }}"@.host /usr/bin/systemctl --user
      enable syncthing
    with_items: "{{ syncthing_usernames }}"

  # Spawn a user manager for each user at system start-up time. This allows
  # enabled user units to start without that user being logged in.
  - name: Enable lingering for certain users
    command: loginctl enable-linger "{{ item }}"
    with_items: "{{ syncthing_usernames }}"

  become: true
