---
- name: Assert that required variables are defined
  assert:
    that:
      - netctl_routers_wan_if is defined
      - netctl_routers_lan_if is defined
      - netctl_routers_dmz_if is defined
      - netctl_routers_wlan_if is defined

- block:

    - name: Install netctl
      pacman:
        name: netctl

    - name: Install netctl profiles
      template:
        src: "{{ item }}"
        dest: /etc/netctl/{{ item }}
      notify: Restart netctl@{{ item }}.service
      loop:
        - dmz
        - lan
        - wan
        - wlan
      register: result

    # This task may look pointless when the systemd module can also enable and
    # disable units. However, netctl does more than systemd:
    #
    # * `netctl enable $profile` also creates a netctl@${profile}.service unit.
    # * `netctl disable $profile` also deletes a netctl@${profile}.service unit.
    # * `netctl reenable $profile` is a combination of `disable` and `enable`.
    #   It's especially useful for updating units. (`netctl enable $profile`
    #   loudly refuses to update existing units.)
    #
    # Thus, `netctl reenable` must be invoked before systemd can work with the
    # desired units.
    - name: Create or update netctl services
      command: netctl reenable {{ item }}
      loop:
        - dmz
        - lan
        - wan
        - wlan
      when: result is changed
      tags: skip_ansible_lint

    - name: Start and enable netctl services
      systemd:
        name: netctl@{{ item }}.service
        state: started
        enabled: true
        daemon_reload: true
      loop:
        - dmz
        - lan
        - wan
        - wlan

  become: true
