- name: Install Subsonic
  pacman:
    name: subsonic
    state: present

- name: Restrict visibility of Subsonic's database
  file:
    path: /var/lib/subsonic/db
    state: directory
    mode: 'o-rwx'

- name: Start and enable Subsonic
  systemd:
    name: subsonic
    state: started
    enabled: yes
