- name: Install AUR packages
  include_role:
    name: user-aur-builder
  vars:
    user_aur_builder_packages:
      - subsonic

- name: Restrict visibility of Subsonic's database
  file:
    path: /var/lib/subsonic/db
    state: directory
    mode: 'o-rwx'

# It'd be *very* nice if Subsonic didn't have visibility into these users'
# files. Perhaps a dedicated user could be created that could host these files?
- name: Let Subsonic see media files
  user:
    name: subsonic
    groups:
      - ichimonji10
      - transmission

- name: Start and enable Subsonic
  systemd:
    name: subsonic
    state: started
    enabled: yes
