---
version: '3.8'

services:
  nginx-browser:
    image: jaudet/nginx-browser
    build: .
    ports:
      - '80'
    volumes:
      - type: bind
        source: /home/ichimonji10/Downloads
        target: /srv/bind-mount
        read_only: true
