- name: Install nftables
  pacman:
    name: nftables
    state: present

- name: Install nftables configuration file
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload nftables

- name: Start and enable nftables
  systemd:
    name: nftables.service
    state: started
    enabled: yes
    daemon_reload: yes
