---
- block:

  - name: Restrict visibility of Airsonic's database
    file:
      path: /var/lib/airsonic/db
      state: directory
      owner: airsonic
      group: airsonic
      mode: 'o-rwx'

  - name: Let Airsonic see media files
    user:
      name: airsonic
      groups:
        - media

  - name: Create a podcasts directory
    file:
      name: /srv/airsonic/podcasts
      state: directory
      owner: airsonic
      group: airsonic

  - name: Customize Airsonic's configuration file
    copy:
      src: airsonic.conf
      dest: /etc/airsonic/
    notify: Restart airsonic

  - name: Install transcoders
    pacman:
      name:
        - ffmpeg
        - flac
        - lame

  - name: Create a directory to link to transcoders
    file:
      path: /var/lib/airsonic/transcode
      state: directory
      owner: airsonic
      group: airsonic

  - name: Link to transcoders
    file:
      path: /var/lib/airsonic/transcode/{{ item }}
      src: /usr/bin/{{ item }}
      state: link
    loop:
      - ffmpeg
      - flac
      - lame

  become: true
