---
- block:

  # A home directory is necessary so that aurutils can cache files in
  # `~/.cache/`, and so that per-user systemd units may be created. (create_home
  # defaults to true.)
  - name: Create {{ custom_repos_user }}
    user:
      name: '{{ custom_repos_user }}'
      home: '{{ custom_repos_user_home }}'
      shell: /usr/bin/nologin
      system: true
    notify: Lock password

  # Required by install-aurutils.sh. Possibly required by aurutils itself for
  # building packages, but this is unclear.
  - name: Give {{ custom_repos_user }} passwordless sudo privileges
    template:
      src: sudoers.d-entry
      dest: /etc/sudoers.d/{{ custom_repos_user }}-user
      validate: 'visudo --check --file %s'
      mode: 0440

  become: true
