---
- name: Install devtools (for makechrootpkg, etc.)
  pacman:
    name: devtools
  become: true

- name: Check if aurutils is installed
  command: pacman -Q aurutils
  changed_when: false
  check_mode: false
  failed_when: false
  register: result

- name: Install aurutils from the AUR
  script: install-aurutils.sh
  become_user: '{{ custom_repos_user }}'
  when: result.rc != 0
  register: result
  become: true
