---
# This sync must be done if the subsequent `pacman -Si …` command is to produce
# valid results.
- name: Sync repository {{ custom_repo.name }}
  command: pacman -Sy --config /etc/pacman.d/{{ custom_repo.name }}.conf
  changed_when: false
  become: true

- name: Check if {{ custom_repo_package }} is packaged
  command: pacman -Si {{ custom_repo.name }}/{{ custom_repo_package }}
  changed_when: false
  check_mode: false
  failed_when: false
  register: result

- block:

  - name: Compile package {{ custom_repo_package }}
    command: >
      aur sync
        --chroot
        --database {{ custom_repo.name }}
        --no-confirm
        --no-view
        {{ custom_repo_package }}
    become_user: '{{ custom_repos_user }}'

  - name: Sync repository {{ custom_repo.name }}
    command: pacman -Sy --config /etc/pacman.d/{{ custom_repo.name }}.conf

  when: result.rc != 0
  become: true
