---
# This sync must be done if the subsequent `pacman -Si …` command is to produce
# valid results.
- name: Sync repository {{ custom_repo_name }}
  command: pacman -Sy --config /etc/pacman.d/{{ custom_repo_name }}.conf
  changed_when: false
  become: true

- name: Check if {{ item }} is packaged
  command: pacman -Si {{ custom_repo_name }}/{{ item }}
  changed_when: false
  check_mode: false
  failed_when: false
  register: result

- block:

  - name: Compile {{ item }}
    command: >
      aur sync
        --database {{ custom_repo_name }}
        --no-confirm
        --no-view
        {{ item }}
    become_user: '{{ custom_repo_user }}'

  - name: Sync repository {{ custom_repo_name }}
    command: pacman -Sy --config /etc/pacman.d/{{ custom_repo_name }}.conf

  when: result.rc != 0
  become: true
