---
- block:

  # Try executing `systemctl list-unit-files | grep update`. You'll find that
  # units named verb-noun are atypical, and units named noun-verb are typical.
  - name: Delete outdated update-repo@ units
    file:
      path: /etc/systemd/system/update-repo@.{{ item }}
      state: absent
    loop:
      - timer
      - service
    register: result

  - name: Reload systemd
    systemd:
      daemon_reload: true
    when: result is changed

  - name: Install service to update repository {{ custom_repo.name }}
    template:
      src: repo-update@.service
      dest: /etc/systemd/system/

  - name: Install timer to update repository {{ custom_repo.name }}
    copy:
      src: repo-update@.timer
      dest: /etc/systemd/system/

  - name: Start and enable timer to update repository {{ custom_repo.name }}
    systemd:
      name: repo-update@{{ custom_repo.name }}.timer
      state: started
      enabled: true
      daemon_reload: true
    when: custom_repo.auto_update | default(custom_repo_auto_update)

  - name: Stop and disable timer to update repository {{ custom_repo.name }}
    systemd:
      name: repo-update@{{ custom_repo.name }}.timer
      state: stopped
      enabled: false
      daemon_reload: true
    when: not (custom_repo.auto_update | default(custom_repo_auto_update))

  become: true
