---
# The file number prefixes have no programmatic effect. They exist to improve
# comprehensibility when browsing files.
- include_tasks: 10-create-user.yml

- include_tasks: 20-install-aurutils.yml

- include_tasks: 30-create-repo.yml
  loop: '{{ custom_repos }}'
  loop_control:
    loop_var: custom_repo

- include_tasks: 40-compile-packages.yml
  loop: '{{ custom_repos }}'
  loop_control:
    loop_var: custom_repo

- include_tasks: 50-integrate-with-systemd.yml
  loop: '{{ custom_repos }}'
  loop_control:
    loop_var: custom_repo

- include_tasks: 60-cleanup.yml
