---
- block:

  - name: 'Install /etc/pacman.d/null.conf'
    copy:
      src: 'etc_pacman.d/null.conf'
      dest: /etc/pacman.d/

  # Routers shouldn't be consuming AUR packages.
  #
  # Webservers host custom repositories, and already have /etc/pacman.d/*.conf
  # files defining how to access said custom repositories.
  - name: Install /etc/pacman.d/ichi-public.conf
    copy:
      src: etc_pacman.d/ichi-public.conf
      dest: /etc/pacman.d/
    notify: Sync pacman
    when:
      - '"routers" not in group_names'
      - '"webservers" not in group_names'

  - name: Install /etc/pacman.conf
    copy:
      src: etc/pacman.conf
      dest: /etc/pacman.conf
    notify: Sync pacman

  - name: Install reflector
    pacman:
      name: reflector

  - name: Install units to update the mirrorlist
    copy:
      src: etc_systemd_system/
      dest: /etc/systemd/system/

  - name: Start and enable timer to update the mirrorlist
    systemd:
      name: update-mirrorlist.timer
      state: started
      enabled: true
      daemon_reload: true

  - name: Install pacman-contrib (for paccache)
    pacman:
      name: pacman-contrib

  - name: Start and enable timer to clean the package cache
    systemd:
      name: paccache.timer
      state: started
      enabled: true
      daemon_reload: true

  become: true
