- block:

  - name: Install btrfs-progs
    pacman:
      name: btrfs-progs
      state: present

  - name: Install units for starting btrfs balances
    template:
      src: '{{ item }}'
      dest: /etc/systemd/system/{{ item }}
    with_items:
      - btrfs-balance.service
      - btrfs-balance.timer

  - name: Start and enable timer for starting btrfs balances
    systemd:
      name: btrfs-balance.timer
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
