---
- name: Assert required variables have been set
  assert:
    that: syncthing_usernames is defined

- block:

    - name: Install syncthing
      pacman:
        name: syncthing

    - name: Set inotify watch limit now and at next boot
      sysctl:
        name: fs.inotify.max_user_watches
        # A 64-bit OS uses about 1 KB of memory per inode.
        value: 65536
        sysctl_file: /etc/sysctl.d/50-syncthing.conf
        state: present
      notify: Set inotify watch limit now

  become: true

- include_tasks: syncthing-for-user.yml
  loop: '{{ syncthing_usernames }}'
