---
- name: Reload NetworkManager
  systemd:
    name: NetworkManager
    state: reloaded
  become: true

- name: Restart dnsmasq
  systemd:
    name: dnsmasq.service
    state: restarted
  become: true

- name: Regenerate /etc/resolv.conf
  command: resolvconf -u
  become: true
