- name: Create users with admin, mail privileges
  user:
    name: ichimonji10
    groups:
      - ichi-machines
      - wheel
  when: "'vm-hosts' not in group_names"

- name: Create users with admin, mail, VM privileges
  user:
    name: ichimonji10
    groups:
      - ichi-machines
      - kvm
      - libvirt
      - wheel
  when: "'vm-hosts' in group_names"

- name: Create users with mail privileges
  user:
    name: googoo
    groups:
      - ichi-machines
  when:
    - "'servers' in group_names"
    - "'routers' not in group_names"
