- name: Install video driver (beech)
  pacman:
    name:
      # See: https://wiki.archlinux.org/index.php/Hardware_video_acceleration
      - mesa-vdpau
      - xf86-video-amdgpu
    state: present
  when: "inventory_hostname == 'beech.ichimonji10.name'"

- name: Install video driver (butternut)
  pacman:
    name:
      # See: https://wiki.archlinux.org/index.php/Hardware_video_acceleration
      - mesa-vdpau
      - xf86-video-amdgpu
    state: present
  when: "inventory_hostname == 'butternut.ichimonji10.name'"

# TODO: Move installation of AUR packages into separate step
# NOTE: We assume base and base-devel are already present, and were enabled at
# install time. Requiring it at a later time can be problematic if the multilib
# repository is enabled.
- name: Install applications
  pacman:
    name:
      - ansible
      - ansible-lint
      - calibre
      - chromium
      - cmark
      - easytag
      - evince
      - exfat-utils
      - file-roller
      - firefox
      - gimp
      - git
      - gptfdisk
      - graphviz
      - gvfs  # optional for thunar
      - hexchat
      - iperf3
      - iw
      - lightdm
      - lightdm-gtk-greeter  # optional for lightdm
      - lightdm-gtk-greeter-settings  # optional for lightdm
      - lshw
      - lsof
      - mnemosyne
      - ms-sys
      - namcap
      - network-manager-applet  # optional for networkmanager
      - networkmanager
      - networkmanager-openvpn  # optional for networkmanager
      - noto-fonts
      - noto-fonts-emoji
      - ntfs-3g
      - openssh
      - pacaur
      - pkgbuild-introspection
      - pulseaudio
      - python-docutils  # for rst2html
      - python-wheel
      - shellcheck
      - sshfs
      - sudo
      - sysstat
      - tmux
      - virt-manager
      - vlc
      - wget
      - xfce4
      - xfce4-goodies
      - xorg-server
    state: present
  notify: Set install reason for optional dependencies

- name: Install lm_sensors
  pacman:
    name: lm_sensors
    state: present
  notify: Detect sensors

# Immediately starting these applications - especially at install time - could
# cause complications.
- name: Enable (but don't start) desirable applications
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - NetworkManager.service
    - lightdm.service
