---
- block:

  - name: Install btrfs-progs
    pacman:
      name: btrfs-progs
      state: present

  - name: Enable periodic btrfs scrubs
    systemd:
      name: btrfs-scrub@{{ item | systemd_escape }}.timer
      state: started
      enabled: true
      daemon_reload: true
    loop: '{{ btrfs_paths }}'

  become: true
