- block:

  - name: Install btrfs-progs
    pacman:
      name: btrfs-progs
      state: present

  - name: Enable periodic btrfs scrubs
    systemd:
      name: btrfs-scrub@{{ btrfs_path | systemd_escape }}.timer
      state: started
      enabled: yes
      daemon_reload: yes

  become: true
