# Standards: 0.1
- hosts: all
  roles:
  - check-units
  - crda
  - essential-apps
  - intel-ucode
  - lm-sensors
  - locale
  - pkgfile
  - reflector
  - smartd
  - time
  - user-ichimonji10

- hosts: dev-hosts
  roles:
  - dev-env
  - nftables-generic
  - syncthing

- hosts: dev-hosts:&servers:&vm-hosts
  roles:
  - coworkers

- hosts: uefi-hosts
  roles:
  - uefi

- hosts: workstations
  roles:
  - borg-backup-users
  - syncthing
  - workstation

- hosts: vm-hosts
  roles:
  - libvirtd

- hosts: docker-hosts
  roles:
  - docker-nftables

- hosts: btrfs-hosts
  roles:
  - btrfs-balance
  - btrfs-scrub
  - btrfs-subvolume

- hosts: servers
  roles:
  - dynamic-dns
  - sshd

- hosts: servers:!routers
  roles:
  - netctl-generic

- hosts: apc-hosts
  roles:
  - apcupsd

- hosts: bittorrent-hosts
  roles:
  - transmission

- hosts: mnemosyne-hosts
  roles:
  - mnemosyne

- hosts: routers
  roles:
  - dnsmasq
  - hostapd  # NOTE: Execute this play only over a wired connection.
  - netctl-routers
  - nftables-routers

- hosts: webservers
  roles:
  - borg-backup-system
  - nginx  # Make sure to install SSL certificates.
  - subsonic
