# Last time I checked, vanilla Arch systems don't ship with these applications.
- name: Install bash and applications named by ~/.bashrc
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - bash
    - vim
    - less
  become_user: root

- name: Create directories named by ~/.bashrc
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Install ~/.bashrc
  copy:
    src: bashrc
    dest: "{{ ansible_user_dir }}/.bashrc"

- name: Install vim and applications named by ~/.vimrc
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ctags
    - vim
    - vim-jellybeans
    - vim-nerdtree
    - vim-tagbar
  become_user: root

- name: Create directories named by ~/.vimrc
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_user_dir }}/.cache/custom-ctags"
    - "{{ ansible_user_dir }}/.vim/undo"
    - "{{ ansible_user_dir }}/code"

- name: Install ~/.vimrc
  template:
    src: vimrc.j2
    dest: "{{ ansible_user_dir }}/.vimrc"
