- name: Create subsonic-backup user
  user:
    name: subsonic-backup
    shell: /usr/bin/nologin
    groups:
      - subsonic
  notify: Lock subsonic-backup's password
  become: true

- name: Get passwd information about subsonic-backup
  getent:
    database: passwd
    key: subsonic-backup
    split: ':'

- name: Set variable referencing subsonic-backup's ID
  set_fact:
    subsonic_backup_id: "{{ getent_passwd['subsonic-backup'][1] }}"

- name: Set variable referencing subsonic-backup's home directory
  set_fact:
    subsonic_backup_home: "{{ getent_passwd['subsonic-backup'][4] }}"

- name: Get subsonic-backup's lingering state
  command: loginctl --property Linger --value show-user subsonic-backup
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

- block:

  - name: Create directories in subsonic-backup's home directory
    file:
      path: "{{ subsonic_backup_home }}/{{ item }}"
      state: directory
    with_items:
      - '.config/systemd/user'
      - '.local/bin'
      - 'backups'

  - name: Install systemd unit files
    template:
      src: "{{ item }}"
      dest: "{{ subsonic_backup_home }}/.config/systemd/user/{{ item }}"
    with_items:
      - subsonic-backup.service
      - subsonic-backup.timer

  # Spawn a user manager for this user at system start-up time. This allows
  # enabled user units to start without that user being logged in.
  - name: Enable lingering for user
    command: loginctl enable-linger subsonic-backup
    when: result.stdout != 'yes'

  # XDG_RUNTIME_DIR must be set, or else the systemd module will be unable to
  # contact the user's DBus instance. In no particular order, see:
  #
  # * https://github.com/ansible/ansible/issues/27631
  # * https://stackoverflow.com/questions/34167257/can-i-control-a-user-systemd-using-systemctl-user-after-sudo-su-myuser
  # * https://uggedal.com/journal/ansible-systemd-user/
  # * https://unix.stackexchange.com/questions/346841/why-does-sudo-i-not-set-xdg-runtime-dir-for-the-target-user
  # * https://www.freedesktop.org/software/systemd/man/pam_systemd.html
  - name: Start and enable periodic backup service for user
    systemd:
      name: subsonic-backup.timer
      state: started
      enabled: true
      user: true
      daemon_reload: true
    environment:
      XDG_RUNTIME_DIR: /run/user/{{ subsonic_backup_id }}

  - name: Install subsonic restore script
    copy:
      src: subsonic-restore.sh
      dest: "{{ subsonic_backup_home }}/.local/bin/subsonic-restore.sh"
      mode: 0755

  become: true
  become_user: subsonic-backup
