---
- block:

  - name: Install apcupsd
    pacman:
      name: apcupsd
      state: present

  # Some of the slow-to-shut-down applications also require power-hungry
  # hardware. Think of a bittorrent client and its storage requirements, or a
  # hypervisor and its compute requirements. As a result, it seems prudent to
  # err on the side of safety and tweak the default configuration file
  # directives, to prevent unclean shutdowns.

  - name: Customize BATTERYLEVEL directive in apcupsd configuration file
    lineinfile:
      path: /etc/apcupsd/apcupsd.conf
      regexp: '^BATTERYLEVEL '
      # Default: 5
      line: 'BATTERYLEVEL 10'
    notify: Restart hostapd

  - name: Customize MINUTES directive in apcupsd configuration file
    lineinfile:
      path: /etc/apcupsd/apcupsd.conf
      regexp: '^MINUTES '
      # Default: 3
      line: 'MINUTES 5'
    notify: Restart hostapd

  - name: Start and enable apcupsd
    systemd:
      name: apcupsd.service
      state: started
      enabled: true
      daemon_reload: true

  become: true
