# This user used to have per-user .timer units.
- name: Get ichimonji10's lingering state
  command: loginctl --property Linger --value show-user ichimonji10
  changed_when: false
  check_mode: false
  register: result

- block:

  - name: Disable lingering for ichimonji10
    command: loginctl disable-linger ichimonji10
    when: result.stdout == 'yes'

  - name: Delete outdated script for checking on units
    file:
      path: "{{ user_ichimonji10_home }}/.local/bin/check-units.sh"
      state: absent

  - name: Delete outdated units for checking on units
    file:
      path: '{{ user_ichimonji10_home }}/.config/systemd/user/{{ item }}'
      state: absent
    with_items:
    - check-units.service
    - check-units.timer

  - name: Create directories named by ~/.bashrc
    file:
      path: "{{ user_ichimonji10_home }}/.local/bin"
      state: directory
    become_user: ichimonji10

  - name: Install ~/.bashrc
    copy:
      src: bashrc
      dest: "{{ user_ichimonji10_home }}/.bashrc"
    become_user: ichimonji10

  - name: Create directories named by ~/.vimrc
    file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ user_ichimonji10_home }}/.cache/custom-ctags"
    - "{{ user_ichimonji10_home }}/.vim/undo"
    - "{{ user_ichimonji10_home }}/code"
    become_user: ichimonji10

  - name: Install ~/.vimrc
    template:
      src: vimrc
      dest: "{{ user_ichimonji10_home }}/.vimrc"
    become_user: ichimonji10

  become: true
