# The "sys" group is for printing. See:
# https://wiki.archlinux.org/index.php/Printing#Configuration
- name: Define a list of ichimonji10's groups
  set_fact:
    user_ichimonji10_groups:
    - ichi-machines
    - sys
    - wheel
  become: true

# "Members of the libvirt group have passwordless access to the RW daemon socket
# by default." See: https://wiki.archlinux.org/index.php/Libvirt#Using_polkit
- name: Append to groups if host in vm-hosts group
  set_fact:
    user_ichimonji10_groups: "{{ user_ichimonji10_groups + ['libvirt'] }}"
  when: "'vm-hosts' in group_names"

- block:

  - name: Install picocom (and create uucp group)
    include_role:
      name: desktop-environment
      tasks_from: picocom

  - name: Append "uucp" to the list of ichimonji10's groups
    set_fact:
      user_ichimonji10_groups: "{{ user_ichimonji10_groups + ['uucp'] }}"

  when: "'workstations' in group_names"

- name: Create ichimonji10
  user:
    name: ichimonji10
    groups: "{{ user_ichimonji10_groups }}"
  become: true

- name: Get information about ichimonji10
  getent:
    database: passwd
    key: ichimonji10
    split: ':'

- name: Set variable referencing ichimonji10's home directory
  set_fact:
    user_ichimonji10_home: "{{ getent_passwd['ichimonji10'][4] }}"

- name: Configure basic unit monitoring for user
  include_role:
    name: check-units
  vars:
    check_units_users:
    - ichimonji10

- include_tasks: all.yml
- include_tasks: vm-hosts.yml
  when: "'vm-hosts' in group_names"
- include_tasks: workstations.yml
  # ansible_hostname is the hostname as reported by a host, and may be short,
  # like 'pine'. Also, pine.ichimonji10.name is used for too many things.
  when: "'workstations' in group_names or inventory_hostname == 'pine.ichimonji10.name'"
