# The "sys" group is for printing. See:
# https://wiki.archlinux.org/index.php/Printing#Configuration
- name: Define a list of groups that ichimonji10 belongs to
  set_fact:
    user_ichimonji10_groups:
    - sys
    - wheel
  become: true

# "Members of the libvirt group have passwordless access to the RW daemon socket
# by default." See: https://wiki.archlinux.org/index.php/Libvirt#Using_polkit
- name: Append "libvirt" to the list of groups
  set_fact:
    user_ichimonji10_groups: "{{ user_ichimonji10_groups + ['libvirt'] }}"
  when: "'vm-hosts' in group_names"

- name: Append "uucp" to the list of groups
  set_fact:
    user_ichimonji10_groups: "{{ user_ichimonji10_groups + ['uucp'] }}"
  when: "'workstations' in group_names"

- name: Create ichimonji10
  user:
    name: ichimonji10
    groups: "{{ user_ichimonji10_groups }}"
  become: true

- name: Get information about ichimonji10
  getent:
    database: passwd
    key: ichimonji10
    split: ':'

- name: Set variable referencing ichimonji10's home directory
  set_fact:
    user_ichimonji10_home: "{{ getent_passwd['ichimonji10'][4] }}"

- include_tasks: all.yml
- include_tasks: vm-hosts.yml
  when: "'vm-hosts' in group_names"
- include_tasks: dev-hosts.yml
  when: "'dev-hosts' in group_names"
