---
- block:

  - name: Create ~/.ssh/
    file:
      path: '{{ user_ichimonji10_home }}/.ssh'
      state: directory
      mode: 0700
    become_user: ichimonji10

  - name: Install public SSH key
    copy:
      dest: '{{ user_ichimonji10_home }}/.ssh/authorized_keys'
      content: '{{ ssh_keypairs[inventory_hostname]["ichimonji10"]["public"] }}'
      mode: 0600
    become_user: ichimonji10

  become: true
