---
- block:

  - name: Remove outdated custom executables
    file:
      path: "{{ user_ichimonji10_home }}/.local/bin/{{ item }}"
      state: absent
    loop:
      - clone-customize-domains
      - clone-customize-domains.sh
      - psmash-runner-2-13-stable
      - psmash-runner-2-14-nightly
      - psmash-runner-2-14-stable
      - psmash-runner-2-15-nightly
      - psmash-runner-2-15-stable
      - psmash-runner-2-16-nightly
      - psmash-runner-2-16-stable
      - psmash-runner-2-17-nightly
      - psmash-runner-3
      - psmash-runner-3-pypi
      - psmash-runner-3-qpid
      - psmash-runner-3-rabbitmq
      - psmash-runner-3-source
      - psmash-runner-beta
      - psmash-runner-clustered
      - psmash-ssh
      - psmash-ssh.py

  - name: Create "{{ user_ichimonji10_home }}/.config/libvirt"
    file:
      state: directory
      path: "{{ user_ichimonji10_home }}/.config/libvirt"

  - name: Install libvirt configuration file
    copy:
      src: libvirt.conf
      dest: "{{ user_ichimonji10_home }}/.config/libvirt/libvirt.conf"

  become: true
  become_user: ichimonji10
