---
- block:

  - name: Install openvpn
    pacman:
      name: openvpn

  - name: Install openvpn configuration file
    copy:
      src: ivpn.conf
      dest: /etc/openvpn/client/ivpn.conf
      mode: 0755

  - name: Install openvpn credentials file
    template:
      src: credentials
      dest: /etc/openvpn/client/credentials
      mode: 0700
    when:
      - openvpn_client_ivpn_username is defined
      - openvpn_client_ivpn_password is defined

  - name: Install routing configuration scripts
    copy:
      src: usr_local_bin/{{ item }}
      dest: /usr/local/bin/{{ item }}
      mode: 0755
    loop:
      - openvpn-route-pre-down.sh
      - openvpn-route-up.sh

  - name: Define the priority of the "tunnel" routing table
    blockinfile:
      path: /etc/iproute2/rt_tables
      create: false
      block: |
        # For openvpn-client@ivpn.
        100 tunnel

  become: true
