- name: Create user
  user:
    name: googoo
    groups:
      - ichi-machines
  become: true

- name: Configure basic unit monitoring for user
  include_role:
    name: check-units
  vars:
    check_units_users:
      - ichimonji10
