- name: Install pkgfile
  pacman:
    name: pkgfile
    state: present

- name: Start and enable timer to update pkgfile database
  systemd:
    name: pkgfile-update.timer
    state: started
    enabled: yes
    daemon_reload: yes
