- name: ensure packages are present
  pacman:
    name: pkgfile
    state: present

- name: ensure timer for updating pkgfile is started and enabled
  systemd:
    name: pkgfile-update.timer
    state: started
    enabled: yes
    daemon_reload: yes
