- name: Set ichimonji10's groups
  set_fact:
    ichimonji10_groups:
      - ichi-machines
      - wheel

- name: Append to groups if host in vm-hosts group
  set_fact:
    ichimonji10_groups: "{{ ichimonji10_groups + ['kvm', 'libvirt'] }}"
  when: "'vm-hosts' in group_names"

- name: Create ichimonji10
  user:
    name: ichimonji10
    groups: "{{ ichimonji10_groups }}"

- name: Get ichimonji10's home directory
  shell: 'getent passwd ichimonji10 | cut -d: -f6'
  check_mode: false
  changed_when: false
  register: result

- name: Set variable referencing ichimonji10's home directory
  set_fact:
    ichimonji10_home: "{{ result.stdout }}"

- include: all.yml
- include: vm-hosts.yml
  when: "'vm-hosts' in group_names"
- include: workstations.yml
  # ansible_hostname is the hostname as reported by a host, and may be short,
  # like 'pine'. Also, pine.ichimonji10.name is used for too many things.
  when: "'workstations' in group_names or inventory_hostname == 'pine.ichimonji10.name'"
