- name: Install git and twine
  pacman:
    name:
      - git
      - twine
  become: true

- block:

  - name: Install git config files
    copy:
      src: "{{ item }}"
      dest: "{{ ichimonji10_home }}/.{{ item }}"
    with_items:
      - gitconfig
      - gitignore_global

  - name: Install ~/.pypirc (for twine)
    copy:
      src: pypirc
      dest: "{{ ichimonji10_home}}/.pypirc"

  become: true
  become_user: ichimonji10

- name: Install AUR packages
  include_role:
    name: user-aur-builder
  vars:
    user_aur_builder_packages:
      - vim-badwolf-git
      - vim-hemisu-git
      - vim-mark
