- name: Install git
  pacman:
    name: git
    state: present

- name: Install git config files
  copy:
    src: "{{ item }}"
    dest: "{{ ichimonji10_home }}/.{{ item }}"
  with_items:
    - gitconfig
    - gitignore_global

- name: Install twine
  pacman:
    name: twine
    state: present

- name: Install ~/.pypirc (for twine)
  copy:
    src: pypirc
    dest: "{{ ichimonji10_home}}/.pypirc"

- name: Check if vim-badwolf-git is installed
  command: pacman -Q vim-badwolf-git
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

- name: Install vim-badwolf-git from the AUR
  command: 'pacaur -S --noconfirm vim-badwolf-git'
  when: result.rc != 0
  become_user: pacaur-builder

- name: Check if vim-hemisu-git is installed
  command: pacman -Q vim-hemisu-git
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

- name: Install vim-hemisu-git from the AUR
  command: 'pacaur -S --noconfirm vim-hemisu-git'
  when: result.rc != 0
  become_user: pacaur-builder

- name: Check if vim-mark is installed
  command: pacman -Q vim-mark
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

- name: Install vim-mark from the AUR
  command: 'pacaur -S --noconfirm vim-mark'
  when: result.rc != 0
  become_user: pacaur-builder
