---
- block:

  - name: Create the media group
    group:
      name: media
      state: present
      system: true

  # /srv/media is a mount point owned by root:root. Here, we assume a directory
  # has been mounted onto it.
  - name: Ensure newly created files have group membership set
    file:
      name: /srv/media
      state: directory
      owner: root
      group: media
      mode: 02770

  - name: Ensure newly created files have group permissions set
    acl:
      state: present
      path: /srv/media
      default: true
      follow: false
      etype: group
      # dirs get rwx, files get rw
      permissions: rwx
      recursive: true

  become: true
