---
- block:

    - name: Install mnemosyne
      pacman:
        name: mnemosyne

    - name: Install python-cheroot, for the mnemosyne sync server
      pacman:
        name: python-cheroot
        state: present
      notify: Set install reason for python-cheroot

    - name: Create a user for the mnemosyne sync server
      user:
        name: '{{ mnemosyne_user }}'
        home: '{{ mnemosyne_user_home }}'
        system: true
        shell: /usr/bin/nologin
      notify: Lock password

    - name: Install mnemosyne-sync-server.service
      template:
        src: mnemosyne-sync-server.service
        dest: /etc/systemd/system/

    - name: Start and enable mnemosyne-sync-server.service
      systemd:
        name: mnemosyne-sync-server.service
        state: started
        enabled: true
        daemon_reload: true

    # Mnemosyne's database must be initialized before mnemosyne_credentials can
    # operate on it. That is why we start and enable the service before
    # executing this task.
    - name: Set mnemosyne's sync server credentials
      mnemosyne_credentials:
        username: '{{ mnemosyne_sync_username }}'
        password: '{{ mnemosyne_sync_password }}'
      become_user: '{{ mnemosyne_user }}'
      notify: Restart mnemosyne sync server
      when:
        - mnemosyne_sync_username is defined
        - mnemosyne_sync_password is defined

  become: true
