---
- block:

    - name: Install hostapd
      pacman:
        name: hostapd

    # When hostapd's configuration file changes, it must be restarted, because
    # many changes aren't taken into account by a simple reload.
    - name: Configure hostapd
      template:
        src: hostapd.conf
        dest: /etc/hostapd/hostapd.conf
        mode: 0600
      notify: Restart hostapd
      when:
        - hostapd_secure_if is defined
        - hostapd_secure_name is defined
        - hostapd_secure_passphrase is defined

    - name: Delete hostapd.service unit override file
      file:
        path: /etc/systemd/system/hostapd.service.d
        state: absent

    - name: Delete wlan-secure.service
      file:
        path: /etc/systemd/system/wlan-secure.service
        state: absent

    - name: Start and enable hostapd
      systemd:
        name: hostapd.service
        state: started
        enabled: true
        daemon_reload: true

  become: true
