- name: Install wlan-secure.service
  copy:
    src: wlan-secure.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Enable wlan-secure.service
  systemd:
    name: wlan-secure.service
    enabled: yes
    daemon_reload: yes
