---
- block:

  - name: Uninstall msmtp
    pacman:
      name:
        - msmtp-mta
        - msmtp
      state: absent

  - name: Delete the msmtp configuration files
    file:
      path: /etc/msmtprc
      state: absent

  - name: Delete the ichi-machines group
    group:
      name: ichi-machines
      state: absent

  become: true
