- name: ensure packages are present
  pacman:
    name: dnsmasq
    state: present

# When dnsmasq receives a SIGHUP signal (as from `systemctl reload`), it does
# *not* re-read its configuration file. See dnsmasq(8).
- name: ensure dnsmasq configuration is present
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dnsmasq

- name: ensure dnsmasq is started and enabled
  systemd:
    name: dnsmasq.service
    state: started
    enabled: yes
    daemon_reload: yes
