# After executing this role, add authorized users to 'kvm' and 'libvirt' groups.

- name: ensure packages are present
  pacman:
    name: '{{ item }}'
    state: present
  with_items:
    - libvirt
    - qemu  # libvirt backend
    - openbsd-netcat  # libvirt management over ssh
    - virt-install  # libvirt management via console (including virt-clone)
    - dnsmasq
  notify:
    - set install reason for packages

- name: ensure dnsmasq has a correct configuration file
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644

- name: ensure local scripts are present
  copy:
    src: usr_local_bin/
    dest: '/usr/local/bin/'
    owner: root
    group: root
    mode: 0755

- name: ensure systemd units are present
  copy:
    src: etc_systemd_system/
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: ensure libvirtd is started and enabled
  systemd:
    name: libvirtd
    state: started
    enabled: yes
    daemon_reload: yes  # due to /etc/systemd/system/ changes above

- name: ensure IPv4 forwarding is enabled now and at next boot
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/50-libvirtd-networking.conf
    state: present
  notify: ensure IPv4 forwarding is enabled right now
