- name: install netctl
  pacman:
    name: netctl
    state: present

- name: install netctl profiles
  copy:
    src: "{{ item }}"
    dest: /etc/netctl/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - dmz
    - lan
    - wan
    - wlan
  register: result

# This step seems redundant in light of the following systemd task. However,
# it's necessary. A netctl@${profile-name}.service systemd unit is created and
# destroyed whenever `netctl enable $profile-name` and `netctl disable
# $profile-name` are executed, respectively. `netctl start $profile-name` and
# `netctl stop $profile-name` do not have any effect on systemd units.
- name: create or update a systemd unit for the netctl profiles
  command: netctl enable {{ item }}
  with_items:
    - dmz
    - lan
    - wan
    - wlan
  when: result|changed

- name: start and enable netctl@ systemd units
  systemd:
    name: netctl@{{ item }}.service
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - dmz
    - lan
    - wan
    - wlan
