- name: Install netctl
  pacman:
    name: netctl
    state: present

- name: Install netctl profiles
  copy:
    src: "{{ item }}"
    dest: /etc/netctl/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - dmz
    - lan
    - wan
    - wlan
  register: result

# The "netctl enable" task seems redundant in light of the following systemd
# tasks. However, it's necessary. A netctl@${profile-name}.service systemd unit
# is created only when `netctl enable $profile-name` is executed, and vice versa
# for deletion. (`netctl start $profile-name` and `netctl stop $profile-name`
# have no effect on systemd units.)
#
# When a systemd unit is created, the first systemd task ensures it starts. When
# a systemd unit is updated, the second systemd task ensures it reloads.
- name: Create or update netctl services
  command: netctl reenable {{ item }}
  with_items:
    - dmz
    - lan
    - wan
    - wlan
  when: result|changed

- name: Start and enable netctl services
  systemd:
    name: netctl@{{ item }}.service
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - dmz
    - lan
    - wan
    - wlan

- name: Reload netctl services
  systemd:
    name: netctl@{{ item }}.service
    state: reloaded
    daemon_reload: yes
  with_items:
    - dmz
    - lan
    - wan
    - wlan
  when: result|changed
