# Last time I checked, vanilla Arch systems don't ship with these applications.
- name: Install bash and applications named by ~/.bashrc
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - bash
    - vim
    - less

- name: Create directories named by ~/.bashrc
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory

- name: Install ~/.bashrc
  copy:
    src: bashrc
    dest: "{{ ansible_user_dir }}/.bashrc"
