- name: ensure packages are present
  pacman:
    name: nftables
    state: present

- name: ensure firewall configuration is present
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nftables

- name: ensure firewall is started and enabled
  systemd:
    name: nftables.service
    state: started
    enabled: yes
    daemon_reload: yes
