# NOTE: Execute this play only over a wired connection.

- name: Install crda and hostapd
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - crda
    - hostapd

- name: Configure crda
  copy:
    src: wireless-regdom
    dest: /etc/conf.d/wireless-regdom
    owner: root
    group: root
    mode: 0644
  register: result

- name: Set wireless regulatory domain
  command: iw reg set US
  when: result|changed

- name: Configure hostapd
  template:
    src: hostapd.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0600
  register: result

# hostapd must be restarted because many changes aren't taken into account by a
# simple reload.
- name: Restart hostapd
  systemd:
    name: hostapd.service
    state: restarted
    daemon_reload: yes
  when: result|changed

- name: Set an IP address on the secondary wlan interface
  systemd:
    name: wlan-secure.service
    state: restarted
    daemon_reload: yes
  when: result|changed

- name: Start and enable hostapd
  systemd:
    name: hostapd.service
    state: started
    enabled: yes
    daemon_reload: yes
