# NOTE: Execute this play only over a wired connection.

- name: Install crda and hostapd
  pacman:
    name:
      - crda
      - hostapd
    state: present

- name: Configure crda
  copy:
    src: wireless-regdom
    dest: /etc/conf.d/wireless-regdom
    owner: root
    group: root
    mode: 0644
  notify: Set wireless regulatory domain

- name: Configure hostapd
  template:
    src: hostapd.j2
    dest: /etc/hostapd/hostapd.conf
    owner: root
    group: root
    mode: 0600
  notify: Set an IP address on the secondary wlan interface
  register: result

# When hostapd's configuration file changes, it must be restarted, because many
# changes aren't taken into account by a simple reload.
#
# Imagine hostapd is stopped:
#
# * If this task were a handler, then the following "start and enable hostapd"
#   task would start hostapd, and the handler would restart it.
# * If this task is left as a task, then this start hostapd, and the following
#   "start and enable hostapd" task doesn't (re)start hostapd.
#
# Thus, we leave this as a task here to avoid an unnecessary hostapd restart.
- name: Restart hostapd
  systemd:
    name: hostapd.service
    state: restarted
    daemon_reload: yes
  when: result|changed
  tags: skip_ansible_lint

- name: Start and enable hostapd
  systemd:
    name: hostapd.service
    state: started
    enabled: yes
    daemon_reload: yes
