# NOTE: Execute this play only over a wired connection.
- block:

  - name: Install hostapd
    pacman:
      name: hostapd

  # When hostapd's configuration file changes, it must be restarted, because
  # many changes aren't taken into account by a simple reload.
  - name: Configure hostapd
    template:
      src: hostapd.conf
      dest: /etc/hostapd/hostapd.conf
      mode: 0600
    notify:
      - Restart hostapd
      - Set an IP address on the secondary wlan interface
    when: hostapd_passphrase is defined

  - name: Start and enable hostapd
    systemd:
      name: hostapd.service
      state: started
      enabled: yes
      daemon_reload: yes

  become: true

- name: Check whether unit file exists
  stat:
    path: /etc/systemd/system/{{ item }}
  loop:
    - log-entropy.service
    - log-entropy.timer
  register: result

- block:

  - name: Stop and disable units for logging entropy
    systemd:
      name: '{{ item.item }}'
      state: stopped
      enabled: false
    when: item.stat.exists
    loop: '{{ result.results }}'

  - name: Delete unit files for logging entropy
    file:
      path: /etc/systemd/system/{{ item.item }}
      state: absent
    when: item.stat.exists
    loop: '{{ result.results }}'
    notify: Reload systemd

  become: true
