---
- block:

  - name: Install nginx
    pacman:
      name: nginx

  - name: Let nginx access transmission's files (esp. downloads)
    user:
      name: http
      groups: transmission
      append: true
      create_home: false

  - name: Delete outdated htpasswd file for transmission.ichimonji10.name
    file:
      path: >-
        /etc/nginx/{{
          'transmission.ichimonji10.name/downloads' | systemd_escape
        }}.htpasswd
      state: absent

  - name: Install htpasswd file for transmission.ichimonji10.name
    htpasswd:
      name: admin
      password: '{{ transmission_password }}'
      path: >-
        /etc/nginx/{{
          'transmission.ichimonji10.name' | systemd_escape
        }}.htpasswd
      owner: root
      group: http
      mode: 0640
    when: transmission_password is defined

  - name: Install htpasswd file for packages.ichimonji10.name/.../ichi-private/
    htpasswd:
      name: anonymous
      password: '{{ pacman_conf_repo_passwords["ichi-private"] }}'
      path: >-
        /etc/nginx/{{
          'packages.ichimonji10.name/arch-linux/ichi-private' | systemd_escape
        }}.htpasswd
      owner: root
      group: http
      mode: 0640
    when: '"ichi-private" in pacman_conf_repo_passwords'

  - name: Install nginx configuration file
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: Reload nginx

  - name: Create directory for SSL certificates
    file:
      path: /etc/nginx/ssl
      state: directory
      mode: 0700

  - name: Install SSL certificates and certificate keys
    copy:
      src: '{{ item }}'
      dest: /etc/nginx/ssl/
      owner: root
      group: root
      mode: 0600
    loop: '{{ nginx_ssl_files }}'
    when: nginx_ssl_files is defined

  # From ansible-doc: The [copy] module recursively copy facility does not scale
  # to lots (>hundreds) of files. For alternative, see [synchronize] module,
  # which is a wrapper around `rsync'.
  - name: Install files for static websites
    copy:
      src: '{{ item }}'
      dest: /usr/share/nginx/
      owner: root
      group: root
      mode: 0644
      directory_mode: 0755
    loop:
      - transmission.ichimonji10.name
      - www.backtobasicsreading.com
      - www.ichimonji10.name

  - name: Start and enable nginx
    systemd:
      name: nginx.service
      state: started
      enabled: true
      daemon_reload: true

  become: true
