---
- block:

    - name: Install borg
      pacman:
        name: borg
        state: present

    - name: Create borg backup system user
      user:
        name: '{{ borg_backup_system_local_user }}'
        home: '{{ borg_backup_system_local_user_home }}'
        shell: /usr/bin/nologin
        system: true
        groups: root
      notify: Lock password

  become: true

- block:

    - name: Create ~/.ssh/
      file:
        path: '{{ borg_backup_system_local_user_home }}/.ssh'
        state: directory
        mode: 0700

    - name: Install private SSH key
      copy:
        src: '{{ borg_backup_system_private_key }}'
        dest: '{{ borg_backup_system_local_user_home }}/.ssh/borg-backup'
        mode: 0600
      when: borg_backup_system_private_key is defined

    - name: Install SSH configuration file
      template:
        src: config
        dest: '{{ borg_backup_system_local_user_home }}/.ssh/'
        mode: 0600
      when:
        - borg_backup_system_remote_host is defined
        - borg_backup_system_remote_user is defined

  become: true
  become_user: '{{ borg_backup_system_local_user }}'

- block:

    - name: Install system-wide Borg backup script
      template:
        src: borg-backup.sh
        dest: /usr/local/bin/
        mode: 0700
        owner: '{{ borg_backup_system_local_user }}'
        group: root
        validate: bash -n %s
      become: true
      when:
        - borg_backup_system_local_paths is defined
        - borg_backup_system_passphrase is defined
        - borg_backup_system_remote_host is defined

    - name: Install borg-backup.service
      template:
        src: borg-backup.service
        dest: /etc/systemd/system/

    - name: Install borg-backup.timer
      copy:
        src: borg-backup.timer
        dest: /etc/systemd/system/

    - name: Start and enable periodic Borg backups
      systemd:
        name: borg-backup.timer
        state: started
        enabled: true
        daemon_reload: true

  become: true
