- name: install netctl
  pacman:
    name: netctl
    state: present

- name: install "external" netctl profile
  copy:
    src: external
    dest: /etc/netctl/external
    owner: root
    group: root
    mode: 0644
  register: result

# The "netctl enable" task seems redundant in light of the following systemd
# tasks. However, it's necessary. A netctl@${profile-name}.service systemd unit
# is created only when `netctl enable $profile-name` is executed, and vice versa
# for deletion. (`netctl start $profile-name` and `netctl stop $profile-name`
# have no effect on systemd units.)
#
# When a systemd unit is created, the first systemd task ensures it starts. When
# a systemd unit is updated, the second systemd task ensures it reloads.
- name: create or update a systemd unit for the "external" netctl profile
  command: netctl reenable external
  when: result|changed

- name: start and enable netctl@external
  systemd:
    name: netctl@external.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: reload netctl@external
  systemd:
    name: netctl@external.service
    state: reloaded
    daemon_reload: yes
  when: result|changed
