---
- block:

    - name: Install libvirt and related tools
      pacman:
        name:
          - libguestfs
          - libvirt
          - openbsd-netcat  # libvirt management over ssh
          - ovmf
          - qemu  # libvirt backend
          - virt-install  # libvirt management via console (incl. virt-clone)
      notify: Set install reason for packages

    - name: Install qemu configuration file
      copy:
        src: qemu.conf
        dest: /etc/libvirt/qemu.conf
        mode: 0755
      notify: Restart libvirtd

    - name: Install units for libvirt and related tools
      copy:
        src: etc_systemd_system/
        dest: /etc/systemd/system/

    - name: Start and enable libvirt
      systemd:
        name: libvirtd
        state: started
        enabled: true
        daemon_reload: true  # due to /etc/systemd/system/ changes above

  become: true
