---
- block:

  - name: Install openssh
    pacman:
      name: openssh

  - name: Install sshd configuration file
    copy:
      src: sshd_config
      dest: /etc/ssh/sshd_config
    notify: Reload sshd

  - name: Start and enable sshd
    systemd:
      name: sshd.service
      state: started
      enabled: true
      daemon_reload: true

  become: true
