---
- name: Lock password
  command: passwd --lock mnemosyne
  become: true

- name: Set install reason for python-cheroot
  command: pacman -D --asdeps python-cheroot
  become: true

- name: Restart mnemosyne sync server
  systemd:
    name: mnemosyne-sync-server.service
    state: restarted
  become: true
