---
- block:

  - name: Install video drivers
    pacman:
      name: '{{ workstation_video_drivers }}'

  # NOTE: We assume base and base-devel are already present, and were enabled at
  # install time. Requiring it at a later time can be problematic if the
  # multilib repository is enabled.
  - name: Install applications
    pacman:
      name:
        - brother-hll2395dw
        - brscan4
        - calibre
        - exfat-utils
        - firefox
        - gptfdisk
        - iperf3
        - lshw
        - lsof
        - mnemosyne
        - ms-sys
        - networkmanager
        - networkmanager-openvpn
        - noto-fonts
        - noto-fonts-emoji
        - ntfs-3g
        - openssh
        - picocom
        - pulseaudio
        - sshfs
        - steam
        - texlive-core  # for mnemosyne
        - ttf-dejavu
        - unzip
        - virt-manager
        - vlc
        - wireshark-qt
        - xclip
        - zip
        - zoom

        # The goal is to *not* pull in the entire KDE desktop environment. So,
        # rather than installing plasma-{meta,kde-applications-meta}, we install
        # a more targeted set of applications and meta-packages. See:
        # https://wiki.archlinux.org/index.php/KDE#Installation
        - dolphin
        - gwenview
        - juk
        - kcalc
        - kcharselect
        - kgraphviewer
        - konsole
        - konversation
        - krita
        - kwrite
        - okular
        - plasma-meta
        - plasma-wayland-session
        - print-manager
        - sddm
        - skanlite
        - spectacle
    notify: Set install reason for optional dependencies

  - name: Uninstall applications
    pacman:
      name:
        - audacious
        - chromium
        - easytag
        - evince
        - file-roller
        - gimp
        - gnome-keyring
        - gvfs  # optional for thunar
        - hexchat
        - light-locker
        - lightdm
        - lightdm-gtk-greeter-settings
        - network-manager-applet
        - p7zip
        - pavucontrol
        - qt4  # formerly for vlc
        - simple-scan
        - unrar
        - wireshark-gtk
        - xfce4
        - xfce4-goodies
      state: absent

  become: true

# Immediately starting these applications - especially at install time - could
# cause complications.
- name: Enable (but don't start) desirable applications
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
  loop:
    - NetworkManager.service
    - sddm.service
  become: true

- name: Enable and start CUPS
  systemd:
    name: org.cups.cupsd
    state: started
    enabled: true
    daemon_reload: true
  become: true
