---
- block:

  - name: Uninstall old video drivers
    pacman:
      name: mesa-vdpau
      state: absent

  - name: Install video drivers
    pacman:
      name: '{{ workstation_video_drivers }}'

  - name: Uninstall applications
    pacman:
      name:
        - audacious
        - chromium
        - dolphin
        - easytag
        - gwenview
        - hexchat
        - juk
        - kcalc
        - kcharselect
        - kgraphviewer
        - konsole
        - konversation
        - krita
        - kwrite
        - light-locker
        - lightdm
        - lightdm-gtk-greeter-settings
        - network-manager-applet
        - okular
        - p7zip
        - pavucontrol
        - plasma-meta
        - plasma-wayland-session
        - print-manager
        - qt4  # formerly for vlc
        - sddm
        - signal
        - skanlite
        - spectacle
        - unrar
        - xfce4
        - xfce4-goodies
        - zoom
      state: absent

  # NOTE: We assume base and base-devel are already present, and were enabled at
  # install time. Requiring it at a later time can be problematic if the
  # multilib repository is enabled.
  - name: Install applications
    pacman:
      name:
        - brother-hll2395dw
        - brscan4
        - calibre
        - exfat-utils
        - firefox
        - gptfdisk
        - iperf3
        - lshw
        - lsof
        - mnemosyne
        - ms-sys
        - networkmanager
        - networkmanager-openvpn
        - noto-fonts
        - noto-fonts-cjk
        - noto-fonts-emoji
        - ntfs-3g
        - openssh
        - picocom
        - pulseaudio
        - signal-desktop-bin
        - sshfs
        - steam
        - texlive-core  # for mnemosyne
        - ttf-dejavu
        - unzip
        - virt-manager
        - vlc
        - wireshark-qt
        - xclip
        - zip

        # The goal is to *not* pull in the entire GNOME desktop. Rather than
        # installing gnome-extra, install gnome and whatever extra apps are
        # desired. See: https://wiki.archlinux.org/index.php/GNOME#Installation
        - gdm
        - gimp
        - gnome

        # https://wiki.archlinux.org/index.php/GStreamer
        - gst-plugins-base
        - gst-plugins-good
        - gstreamer
        - gstreamer-vaapi
    notify: Set install reason for optional dependencies

  become: true

# Immediately starting these applications - especially at install time - could
# cause complications.
- name: Enable (but don't start) desirable applications
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
  loop:
    - NetworkManager.service
    - gdm.service
  become: true

- name: Enable and start CUPS
  systemd:
    name: org.cups.cupsd
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Enable and start bluetooth
  systemd:
    name: bluetooth.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
