---
- block:

  - name: Install video drivers
    pacman:
      name: '{{ workstation_video_drivers }}'

  - name: Uninstall unused packages
    pacman:
      name:
        - chromium
        - p7zip
        - unrar
      state: absent

  # NOTE: We assume base and base-devel are already present, and were enabled at
  # install time. Requiring it at a later time can be problematic if the
  # multilib repository is enabled.
  #
  # To integrate light-locker with XFCE:
  # https://wiki.archlinux.org/index.php/Xfce#Panel_lock_button
  - name: Install applications
    pacman:
      name:
        - audacious
        - brother-hll2395dw
        - brscan4
        - calibre
        - easytag
        - evince
        - exfat-utils
        - file-roller
        - firefox
        - gimp
        - gnome-keyring
        - gptfdisk
        - gvfs  # optional for thunar
        - hexchat
        - iperf3
        - light-locker  # see comments above
        - lightdm
        - lightdm-gtk-greeter-settings
        - lshw
        - lsof
        - mnemosyne
        - ms-sys
        - network-manager-applet
        - networkmanager
        - networkmanager-openvpn
        - noto-fonts
        - noto-fonts-emoji
        - ntfs-3g
        - openssh
        - pavucontrol
        - picocom
        - pulseaudio
        - qt4  # for vlc
        - simple-scan
        - sshfs
        - steam
        - system-config-printer
        - texlive-core  # for mnemosyne
        - ttf-dejavu
        - virt-manager
        - vlc
        - xclip
        - xfce4
        - xfce4-goodies
        - xorg-server
        - zoom
    notify: Set install reason for optional dependencies

  become: true

# Immediately starting these applications - especially at install time - could
# cause complications.
- name: Enable (but don't start) desirable applications
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
  loop:
    - NetworkManager.service
    - lightdm.service
  become: true

- name: Enable and start CUPS
  systemd:
    name: org.cups.cupsd
    state: started
    enabled: true
    daemon_reload: true
  become: true
