- name: Install btrfs-progs
  pacman:
    name: btrfs-progs
    state: present

- name: Install units for starting btrfs scrubs
  copy:
    src: etc_systemd_system/
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644

- name: Start and enable timer for starting btrfs scrubs
  systemd:
    name: btrfs-scrub.timer
    state: started
    enabled: yes
    daemon_reload: yes
