---
- name: Verify required variables are present
  assert:
    that:
      - dnsmasq_lan_if is defined
      - dnsmasq_dmz_if is defined
      - dnsmasq_secure_wlan_if is defined

- block:

    - name: Install stubby
      pacman:
        name: stubby
        state: present

    - name: Install stubby configuration file
      copy:
        src: stubby.yml
        dest: /etc/stubby/

    - name: Start and enable stubby
      systemd:
        name: stubby.service
        state: started
        enabled: true
        daemon_reload: true

  become: true

- include_tasks: resolvconf-dnsmasq.yml
