- hosts: all
  roles:
    - msmtp
    - nftables
    - pkgfile
    - reflector
    - smartd
    - time

- hosts: servers
  roles:
    - sshd
    - role: dynamic-dns
      when: dynamic_dns_urls is defined

- hosts: servers:!routers
  roles:
    - netctl-generic
    - role: openvpn-client-ivpn
      when:
        - openvpn_client_ivpn_username is defined
        - openvpn_client_ivpn_password is defined

- hosts: routers
  roles:
    - dnsmasq
    # NOTE: Execute this play only over a wired connection.
    - role: hostapd
      when: hostapd_passphrase is defined
    - netctl-routers
    - wlan-secure

- hosts: vm-hosts
  roles:
    # NOTE: After running, add authorized users to appropriate groups.
    - libvirtd

- hosts: btrfs-hosts
  roles:
    # NOTE: /mnt/btrfs must be present.
    - btrfs-scrub
    - role: btrfs-snapshot
      when: btrfs_snapshot
