# TODO: Create roles to create users.

- hosts: all
  roles:
    - customize-ichimonji10-all
  become_user: ichimonji10

- hosts: vmhosts
  roles:
    - customize-ichimonji10-vmhosts
  become_user: ichimonji10
