# TODO: Create roles to create users.

- hosts: all
  roles:
    - customize-ichimonji10-all
  become_user: ichimonji10

- hosts: vm-hosts
  roles:
    - customize-ichimonji10-vm-hosts
  become_user: ichimonji10

- hosts: pine.ichimonji10.name
  roles:
    # TODO: Make role generic enough for use with other users.
    # NOTE: Ensure user has an SSH key for logging into remote backup hosts.
    - role: borg-backup
      when: borg_backup_passphrase is defined
  become_user: ichimonji10
  vars:
    borg_backup_directories:
      - ~/books
      - ~/docs
      - ~/pictures

- hosts: pine.ichimonji10.name
  roles:
    - role: borg-backup
      when: borg_backup_passphrase is defined
  become_user: googoo
