# TODO: Create roles to create users.

- hosts: all
  roles:
    - customize-ichimonji10-all
  become_user: ichimonji10

- hosts: vm-hosts
  roles:
    - customize-ichimonji10-vm-hosts
  become_user: ichimonji10
