# After running msmtp role, add authorized users to ichi-machines group.
- hosts: all
  roles:
    - pkgfile
    - reflector
    - smartd
    - role: msmtp
      when: msmtprc_password is defined

- hosts: routers
  roles:
    - nftables-routers
    - dnsmasq
    - role: hostapd
      when: hostapd_passphrase is defined

- hosts: workstations
  roles:
    - nftables-workstations

# After running libvirtd role, add authorized users to appropriate groups.
- hosts: vmhosts
  roles:
    - nftables-vmhosts
    - libvirtd

# /mnt/btrfs must be present.
- hosts: btrfs-hosts
  roles:
    - btrfs-scrub
