- hosts: all
  roles:
    - pkgfile
    - reflector
    - smartd
    # NOTE: After running, add authorized users to ichi-machines group.
    - role: msmtp
      when: msmtprc_password is defined

- hosts: routers
  roles:
    - nftables-routers
    - dnsmasq
    # NOTE: Execute this play only over a wired connection.
    - role: hostapd
      when: hostapd_passphrase is defined
    - sshd
    - wlan-secure
    - netctl-routers

- hosts: workstations
  roles:
    - nftables-generic

- hosts: vmhosts
  roles:
    - nftables-vmhosts
    # NOTE: After running, add authorized users to appropriate groups.
    - libvirtd
    - sshd
    - netctl-generic

# /mnt/btrfs must be present.
- hosts: btrfs-hosts
  roles:
    - btrfs-scrub
