# TODO:
#
# * Create a role named "create-users."
# * Create a host group named "workstation-hosts." Customize user accounts based
#   on host roles.

- hosts: all
  roles:
    - customize-ichimonji10-all
  become_user: ichimonji10
