# TODO: Add ability to configure user passwords. Consider the case where a
# user's authentication scheme should be locked, like `passwd --lock ...`.

- hosts: all:!vm-hosts
  tasks:
    - name: Create users with admin, mail privileges
      user:
        name: ichimonji10
        groups:
          - wheel
          - ichi-machines

- hosts: vm-hosts
  tasks:
    - name: Create users with admin, mail, VM privileges
      user:
        name: ichimonji10
        groups:
          - wheel
          - ichi-machines
          - kvm
          - libvirt

- hosts: servers:!routers
  tasks:
    - name: Create users with mail privileges
      user:
        name: googoo
        groups:
          - ichi-machines

- hosts: all
  roles:
    - customize-ichimonji10-all
  become_user: ichimonji10

- hosts: vm-hosts
  roles:
    - customize-ichimonji10-vm-hosts
  become_user: ichimonji10

- hosts: pine.ichimonji10.name
  roles:
    # NOTE: Ensure user has an SSH key for logging into remote backup hosts.
    - role: borg-backup
      when:
        - borg_backup_passphrase is defined
        - borg_backup_user is defined
  vars:
    borg_backup_directories:
      - ~/books
      - ~/docs
      - ~/pictures
    borg_backup_user: ichimonji10

- hosts: pine.ichimonji10.name
  roles:
    # NOTE: Ensure user has an SSH key for logging into remote backup hosts.
    - role: borg-backup
      when:
        - borg_backup_passphrase is defined
        - borg_backup_user is defined
  vars:
    borg_backup_user: googoo

- hosts: pine.ichimonji10.name
  roles:
    - subsonic

- hosts: pine.ichimonji10.name
  roles:
    # NOTE: Ensure user has an SSH key for logging into remote backup hosts.
    - role: borg-backup
      when:
        - borg_backup_passphrase is defined
        - borg_backup_user is defined
  vars:
    borg_backup_directories:
      - ~/backups
    borg_backup_user: subsonic-backup
