- hosts: all
  roles:
    # before running: edit the vars for this role
    # after running: edit group membership for system users
    - role: msmtp
      when: msmtprc_password is defined

    # No special requirements.
    - pkgfile
    - reflector
    - smartd

- hosts: vm-hosts
  roles:
    # after running: edit group membership for system users, and ensure nftables
    # firewall rules are correct. (Check "chain input" and "table nat".)
    - libvirtd

- hosts: btrfs-hosts
  roles:
    # /mnt/btrfs must be present
    - btrfs-scrub

- hosts: nftables-hosts
  roles:
    - nftables

# vim:set ts=2 sw=2 et:
