- hosts: all
  roles:
    - pkgfile
    - reflector
    - smartd

    # after running: add authorized users to ichi-machines group
    - role: msmtp
      when: msmtprc_password is defined

- hosts: vm-hosts
  roles:
    # NOTE: Members of this group require specific firewall rules. Be careful.
    # after running: add authorized users to appropriate groups
    - libvirtd

- hosts: btrfs-hosts
  roles:
    # /mnt/btrfs must be present
    - btrfs-scrub

- hosts: nftables-hosts
  roles:
    - nftables

- hosts: pine.ichimonji10.name
  roles:
    - nftables-pine.ichimonji10.name

- hosts: amelanchier.ichimonji10.name
  roles:
    - nftables-amelanchier.ichimonji10.name
    - dnsmasq-amelanchier.ichimonji10.name
