- hosts: all
  roles:
    # before running: edit the vars for this role
    # after running: edit group membership for system users
    - msmtp

    # No special requirements.
    - smartd

    # No special requirements.
    - pkgfile

    # No special requirements.
    - reflector
  vars:
    - msmtprc_password: 'FIXME'

- hosts: vm-hosts
  roles:
    # after running: edit group membership for system users, and ensure nftables
    # firewall rules are correct. (Check "chain input" and "table nat".)
    - libvirtd

- hosts: btrfs-hosts
  roles:
    # /mnt/btrfs must be present
    - btrfs-scrub

# vim:set ts=2 sw=2 et:
