# A playbook for all of the problematic roles.
#
# There's a number of reasons that a role might be problematic. One reason might
# be that a role always produces a "changed" state, even when nothing has
# changed.
- hosts: all:!routers
  roles:
    - role: syncthing
      when: syncthing_usernames is defined
  vars:
    syncthing_usernames:
      - ichimonji10

- hosts: pine.ichimonji10.name
  roles:
    - role: syncthing
      when: syncthing_usernames is defined
  vars:
    syncthing_usernames:
       - googoo
