- hosts: all
  roles:
    - check-units
    - crda
    - intel-ucode
    - lm-sensors
    - locale
    - pkgfile
    - reflector
    - smartd
    - time
    - user-ichimonji10
  tasks:
    - name: Install useful applications
      pacman:
        name:
          - bind-tools
          - tree
      become: true

- hosts: all:!routers
  roles:
    - nftables-generic
    - name: aur
      vars:
        aur_packages:
          - entr
    - name: syncthing
      vars:
        syncthing_usernames:
          - ichimonji10

- hosts: all:!amelanchier.ichimonji10.name
  roles:
    - name: aur
      vars:
        aur_packages:
          - systemd-boot-pacman-hook

- hosts: workstations
  roles:
    - desktop-environment
    - picocom

- hosts: vm-hosts
  roles:
    - libvirtd

- hosts: btrfs-hosts
  roles:
    - btrfs-balance
    - btrfs-scrub

# Why make an intersection between a group and a single host, instead of simply
# listing a single host? Well, what if this host is removed from the group?
- hosts: btrfs-hosts:&pine.ichimonji10.name
  roles:
    - name: btrfs-subvolume
      vars:
        btrfs_subvolumes:
          - path: '{{ btrfs_path }}/home'
          - path: '{{ btrfs_path }}/root'
            days: 5
            weeks: 2
            snapshot: false
          - path: '{{ btrfs_path }}/srv/subsonic'
            days: 5
            weeks: 2
          - path: '{{ btrfs_path }}/var/lib/transmission'
            days: 5
            weeks: 2

- hosts: servers
  roles:
    - sshd
    - dynamic-dns

- hosts: servers:!routers
  roles:
    - netctl-generic

- hosts: servers:beech.ichimonji10.name
  roles:
    - apcupsd

- hosts: bittorrent-hosts
  roles:
    - transmission

- hosts: routers
  roles:
    - dnsmasq
    - hostapd  # NOTE: Execute this play only over a wired connection.
    - netctl-routers
    - nftables-routers
    - wlan-secure

- hosts: webservers
  roles:
    - nginx  # Make sure to install SSL certificates.
    - user-subsonic-backup  # depends on "subsonic" role

# Host-specific rules ----------------------------------------------------------

- hosts: pine.ichimonji10.name
  roles:
    - user-googoo
    - name: syncthing
      vars:
        syncthing_usernames:
          - googoo

- hosts: pine.ichimonji10.name
  roles:
    - role: borg-backup
      when:
        - borg_backup_user is defined
      vars:
        borg_backup_directories:
          - ~/books
          - ~/docs
          - ~/pictures
        borg_backup_user: ichimonji10

- hosts: pine.ichimonji10.name
  roles:
    - role: borg-backup
      when:
        - borg_backup_user is defined
      vars:
        borg_backup_user: googoo

- hosts: pine.ichimonji10.name
  roles:
    - role: borg-backup
      when:
        - borg_backup_user is defined
      vars:
        borg_backup_directories:
          - ~/backups
        borg_backup_user: subsonic-backup
