- block:

  - name: Restrict visibility of Subsonic's database
    file:
      path: /var/lib/subsonic/db
      state: directory
      owner: subsonic
      group: subsonic
      mode: 'o-rwx'

  # It'd be *very* nice if Subsonic didn't have visibility into these users'
  # files. Perhaps a dedicated user could be created that could host these files?
  - name: Let Subsonic see media files
    user:
      name: subsonic
      groups:
      - ichimonji10
      - transmission

  - name: Create a podcasts directory
    file:
      name: /srv/subsonic/podcasts
      state: directory
      owner: subsonic
      group: subsonic

  # We customize the config file by setting several environment variables.
  - name: Customize Subsonic's configuration file
    copy:
      src: etc_systemd_system/subsonic.service.d
      dest: /etc/systemd/system/
    notify: Restart subsonic

  - name: Install transcoders
    pacman:
      name:
      - ffmpeg
      - flac
      - lame

  - name: Create a directory to link to transcoders
    file:
      path: /var/lib/subsonic/transcoders
      state: directory
      owner: subsonic
      group: subsonic

  - name: Link to transcoders
    file:
      path: /var/lib/subsonic/transcoders/{{ item }}
      src: /usr/bin/{{ item }}
      state: link
    with_items:
    - ffmpeg
    - flac
    - lame

  become: true
