- block:

  - name: Delete the user that used to perform backups
    user:
      name: subsonic-backup
      state: absent
      remove: true

  # Let root own the directory to ensure that the Subsonic application can't
  # touch the backup scripts, even if it's compromised.
  - name: Create directory for Subsonic database backups
    file:
      path: '{{ item }}'
      state: directory
      owner: root
      group: root
    with_items:
    - /var/local/subsonic
    - /var/local/subsonic/backups

  - name: Install units to periodically back up Subsonic's database
    copy:
      src: etc_systemd_system/{{ item }}
      dest: /etc/systemd/system/{{ item }}
    with_items:
    - subsonic-backup.service
    - subsonic-backup.timer

  - name: Start and enable timer to periodically back up Subsonic's database
    systemd:
      name: subsonic-backup.timer
      state: started
      enabled: true
      daemon_reload: true

  - name: Install script for restoring Subsonic's database
    copy:
      src: restore-subsonic.sh
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: 0755

  become: true
