---
- name: Install subsonic
  pacman:
    name: subsonic
  become: true

- include_tasks: configure-subsonic.yml
- include_tasks: configure-backups.yml

- name: Start and enable Subsonic
  systemd:
    name: subsonic
    state: started
    enabled: true
  become: true
