---
- block:

  - name: Uninstall Subsonic
    pacman:
      name: subsonic
      state: absent

  - name: Delete {{ item }}
    file:
      path: '{{ item }}'
      state: absent
    loop:
      - /etc/systemd/system/subsonic-backup.service
      - /etc/systemd/system/subsonic-backup.timer
      - /etc/systemd/system/subsonic.service.d
      - /srv/subsonic
      - /usr/local/bin/restore-subsonic.sh
      - /var/lib/subsonic
      - /var/local/subsonic

  - name: Delete subsonic user
    user:
      name: subsonic
      state: absent
      remove: true

  become: true
