---
- block:

  - name: Delete old units
    file:
      path: /etc/systemd/system/reflector-update.{{ item }}
      state: absent
    loop:
      - service
      - timer
    register: result

  - name: Reload systemd
    systemd:
      daemon_reload: true
    when: result is changed

  - name: Install reflector
    pacman:
      name: reflector

  - name: Install units to update mirrorlist
    copy:
      src: etc_systemd_system/
      dest: /etc/systemd/system/

  - name: Start and enable timer to update mirrorlist
    systemd:
      name: update-mirrorlist.timer
      state: started
      enabled: true
      daemon_reload: true

  become: true
