---
- block:

  - name: Install reflector
    pacman:
      name: reflector

  - name: Install units for reflector
    copy:
      src: etc_systemd_system/
      dest: /etc/systemd/system/

  - name: Start and enable timer for reflector
    systemd:
      name: reflector-update.timer
      state: started
      enabled: true
      daemon_reload: true

  become: true
