---
- block:

  - name: Delete check-units.{timer,service}
    file:
      path: /etc/systemd/system/check-units.{{ item }}
      state: absent
    loop:
      - timer
      - service
    notify: Reload systemd

  - name: Delete check-units.sh
    file:
      path: /usr/local/bin/check-units.sh
      state: absent

  become: true
