directory: ~/music
plugins: inline fetchart chroma

# Create a custom field, available for use in the "path" configuration section.
item_fields:
    album_and_disc:
        u'{} (CD {})'.format(album, disc)
        if disctotal > 1
        else u'{}'.format(album)

# When an album contains multiple discs, create a separate folder for each disc.
per_disc_numbering: yes
paths:
    default: $albumartist/$album_and_disc%aunique{}/$track $title
