# pacaur caches files in `~/.cache/pacaur`. Thus, a home directory should be
# present. (The user module creates one by default.) Even with no shell and a
# locked password, commands like `become: pacaur-builder, command: 'echo foo'`
# still work.
- name: Create user
  user:
    name: pacaur-builder
    shell: /usr/bin/nologin
  notify: Lock password

# pacaur builds packages as an unprivileged user, then installs files as root.
# In fact, it refuses to run as root. Thus, passwordless sudo must be available.
- name: Give user passwordless sudo privileges
  lineinfile:
    path: /etc/sudoers
    regexp: '^pacaur-builder '
    line: 'pacaur-builder ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo --check --file %s'
