- name: Install msmtp and related tools
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - msmtp
    - msmtp-mta
    - s-nail
  notify:
    - Set install reason for packages

- name: Create a group authorized to send emails
  group:
    name: ichi-machines
    state: present

- name: Install msmtp configuration file
  template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: ichi-machines
    mode: 0640
