- block:

  - name: Install devtools (for makechrootpkg, etc.)
    pacman:
      name: devtools

  # aurutils caches files in `~/.cache/`. Thus, a home directory should be
  # present. (The user module creates one by default.)
  - name: Create user
    user:
      name: aur-packager
      shell: /usr/bin/bash
    notify: Lock password

  # Necessary so that `makepkg --syncdeps` works. Also used by shell script below.
  - name: Give user passwordless sudo privileges
    lineinfile:
      path: /etc/sudoers
      regexp: '^aur-packager '
      line: 'aur-packager ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo --check --file %s'

  become: true

- name: Check if aurutils is installed
  command: pacman -Q aurutils
  changed_when: False
  check_mode: False
  failed_when: False
  register: result

- block:

  - name: Install aurutils from the AUR
    shell: |
      set -euo pipefail

      # Create a workspace, and schedule it for deletion.
      cleanup() { if [ -n "${workspace:-}" ]; then rm -rf "${workspace}"; fi }
      trap cleanup EXIT  # bash pseudo signal
      trap 'cleanup ; trap - SIGINT ; kill -s SIGINT $$' SIGINT
      trap 'cleanup ; trap - SIGTERM ; kill -s SIGTERM $$' SIGTERM
      workspace="$(mktemp --directory)"

      # Alad Wenter (https://aur.archlinux.org/account/Alad)
      gpg --recv-keys DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A

      # Get, build and install aurutils and its deps.
      cd "${workspace}"
      wget 'https://aur.archlinux.org/cgit/aur.git/snapshot/aurutils.tar.gz'
      tar xzf aurutils.tar.gz
      cd aurutils
      makepkg --noconfirm --syncdeps
      sudo pacman -U --noconfirm aurutils-*.pkg.tar.xz
    args:
      executable: /usr/bin/bash
    become_user: aur-packager
    when: result.rc != 0
    register: result

  - name: Create /var/cache/pacman/aur/
    file:
      path: /var/cache/pacman/aur
      state: directory
      owner: aur-packager
      group: aur-packager
      mode: 0755

  - name: Create /var/cache/pacman/aur/aur.db.tar
    command: repo-add /var/cache/pacman/aur/aur.db.tar
    args:
      creates: /var/cache/pacman/aur/aur.db.tar
    become_user: aur-packager

  - name: Install /etc/pacman.d/aur.conf
    copy:
      src: aur.conf
      dest: /etc/pacman.d/aur.conf

  - name: Make /etc/pacman.conf include /etc/pacman.d/aur.conf
    lineinfile:
      path: /etc/pacman.conf
      line: Include = /etc/pacman.d/aur.conf
    register: result

  # If a repository is defined in /etc/pacman.conf, but that repository has never
  # been synced, then pacman will produce errors.
  - name: Sync aur repository
    command: pacman -Sy --config /etc/pacman.d/aur.conf
    when: result | changed

  become: true

- include_tasks: package-and-install.yml
  with_items: '{{ aur_packages }}'
