# The AUR update service was initially implemented as a --user service. We need
# to make sure that that service and supporting services are not running before
# proceeding.
- name: Get {{ aur_user }} lingering state
  command: loginctl --property Linger --value show-user {{ aur_user }}
  changed_when: false
  check_mode: false
  failed_when: false
  register: result

- block:

  - name: Delete {{ aur_user_home }}/.config/systemd/user/
    file:
      path: '{{ aur_user_home }}/.config/systemd/user/'
      state: absent

  - name: Disable lingering for {{ aur_user }}
    command: loginctl disable-linger {{ aur_user }}
    when: result.stdout == 'yes'

  become: true
  become_user: '{{ aur_user }}'

- block:

  - name: Install units to update AUR packages
    template:
      src: update-aur-packages.{{ item }}
      dest: /etc/systemd/system/
    loop:
    - service
    - timer

  - name: Start and enable units to update AUR packages
    systemd:
      name: update-aur-packages.timer
      state: started
      enabled: true
      daemon_reload: true

  become: true
