---
- block:

  - name: Delete update-aur-packages units
    file:
      path: /etc/systemd/system/update-aur-packages.{{ item }}
      state: absent
    loop:
      - timer
      - service
    register: result

  - name: Reload systemd
    systemd:
      daemon_reload: true
    when: result is changed

  - name: Strip sudo privileges from {{ aur_user }}
    file:
      path: /etc/sudoers.d/{{ aur_user }}-user
      state: absent

  - name: Delete user {{ aur_user }}
    user:
      name: '{{ aur_user }}'
      state: absent
      remove: true

  - name: Drop reference to /etc/pacman.d/aur.conf from /etc/pacman.conf
    lineinfile:
      path: /etc/pacman.conf
      line: Include = /etc/pacman.d/aur.conf
      state: absent

  - name: Delete /etc/pacman.d/aur.conf
    file:
      path: /etc/pacman.d/aur.conf
      state: absent

  - name: Delete /var/cache/pacman/aur
    file:
      path: /var/cache/pacman/aur
      state: absent

  become: true
