- block:

  - name: Install a script to delete old subvolumes
    copy:
      src: btrfs-subvolume-delete.py
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: 0755

  - name: Install .service to delete old snapshots of {{ item.path }}
    template:
      src: btrfs-subvolume-delete.service
      dest: /etc/systemd/system/btrfs-subvolume-delete-{{ item.escaped_path }}.service
      owner: root
      group: root
      mode: 0644
    vars:
      path: '{{ item.path }}'
      days: '{{ item.days|default(14) }}'
      weeks: '{{ item.weeks|default(8) }}'

  - name: Install .timer to delete old snapshots of {{ item.path }}
    template:
      src: btrfs-subvolume-delete.timer
      dest: /etc/systemd/system/btrfs-subvolume-delete-{{ item.escaped_path }}.timer
      owner: root
      group: root
      mode: 0644
    vars:
      path: '{{ item.path }}'

  - name: Start and enable .timer to delete old snapshots of {{ item.path }}
    systemd:
      name: btrfs-subvolume-delete-{{ item.escaped_path }}.timer
      state: started
      enabled: yes
      daemon_reload: yes

  when: item.delete | default(true)
