# There's three conerns to consider when deciding how to name units:
#
# * Compatibility. Various file systems place restrictions on which characters
#   may appear in file names. Unit names should use a conservative set of
#   characters, so as to avoid violating compatibility constraints.
# * Uniqueness. Unit names should never conflict with each other.
# * Usability. Unit names should be human-readable.
#
# A hash is compatible and unique. A (good) path transformation is compatible
# and usable. This module uses the path transformations provided by
# systemd-escape(1). The control host must have this executable available.

- name: Install btrfs-progs
  pacman:
    name: btrfs-progs
    state: present

- name: Set escaped paths for btrfs subvolumes
  set_fact:
    btrfs_subvolumes: '{{ btrfs_subvolumes | set_escaped_paths }}'

- name: Install a script to delete old subvolumes
  copy:
    src: btrfs-subvolume-delete.py
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755

- name: Install .service units to delete old subvolumes
  template:
    src: btrfs-subvolume-delete.service
    dest: /etc/systemd/system/btrfs-subvolume-delete-{{ item.escaped_path }}.service
    owner: root
    group: root
    mode: 0644
  vars:
    path: "{{ item.path }}"
    days: "{{ item.days|default(14) }}"
    weeks: "{{ item.weeks|default(8) }}"
  with_items: "{{ btrfs_subvolumes }}"

- name: Install .timer units to delete old subvolumes
  template:
    src: btrfs-subvolume-delete.timer
    dest: /etc/systemd/system/btrfs-subvolume-delete-{{ item.escaped_path }}.timer
    owner: root
    group: root
    mode: 0644
  vars:
    path: "{{ item.path }}"
  with_items: "{{ btrfs_subvolumes }}"

- name: Start and enable .timer units to delete old subvolumes
  systemd:
    name: btrfs-subvolume-delete-{{ item.escaped_path }}.timer
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ btrfs_subvolumes }}"

- name: Install .service units to snapshot subvolumes
  template:
    src: btrfs-subvolume-snapshot.service
    dest: /etc/systemd/system/btrfs-subvolume-snapshot-{{ item.escaped_path }}.service
    owner: root
    group: root
    mode: 0644
  vars:
    path: "{{ item.path }}"
  with_items: "{{ btrfs_subvolumes }}"

- name: Install .timer units to snapshot subvolumes
  template:
    src: btrfs-subvolume-snapshot.timer
    dest: /etc/systemd/system/btrfs-subvolume-snapshot-{{ item.escaped_path }}.timer
    owner: root
    group: root
    mode: 0644
  vars:
    path: "{{ item.path }}"
  with_items: "{{ btrfs_subvolumes }}"

- name: Start and enable .timer units to snapshot subvolumes
  systemd:
    name: btrfs-subvolume-snapshot-{{ item.escaped_path }}.timer
    state: started
    enabled: yes
    daemon_reload: yes
  with_items: "{{ btrfs_subvolumes }}"
