- name: Install borg and its dependencies
  pacman:
    name:
    - borg
    - openssh  # for connecting to borg repositories on remote hosts
  become: true

- include_tasks: configure-user.yml
  loop: '{{ borg_backups }}'
  loop_control:
    loop_var: borg_backup
